### ISSUE TITLE
Rover: DSHOT reverse range is inverted

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#19346]
When trying to use Reversable Shot motors with rover firmware the reverse values are inverted.

0-100% forward should be 1500-2000us output and that works fine.
 0-100% reverse ends up as 1000-1500us so as minimum speed reverse is 1000us and full speed reverse is 1500us rather than minimum reverse at 1500us and full reverse at 1000us 
 
SERVO_DSHOT_ESC was set to 1, when set to 0 reverse done nothing.

Regular PWM mode works as expected but it disables ESC telemetry.
so far I have only seen it in 4.2 dev downgrading to 4.11 works as expected.
blheli32 32.8

**Comment by rmackay9** [comment]
FYI @andyp1per

**Comment by geofrancis** [comment]
is there any specific reason Dshot needs to be enabled to get blheli32 telemetry?

**Comment by andyp1per** [comment]
> is there any specific reason Dshot needs to be enabled to get blheli32 telemetry? or is it just assumed that if they have a telemetry capable esc they want to use dshot?

Yes, requesting telemetry is part of the dshot protocol - it is not part of any of the other protocols. It's possible, I suppose, that BLHeli's auto telemetry feature might help here, but we are not currently geared up to cope with that.

**Comment by andyp1per** [comment]
I'm having a hard time believing this is different in 4.2 - the dshot code for 4.2 and 4.1 is very little changed and the place we convert for reversing motors is almost identical. Please can you post your full parameter list so that I can test?

**Comment by andyp1per** [comment]
@shellixyz you are using reversing motors on 4.2 I believe?

**Comment by geofrancis** [comment]
I'm trying to replicate it, but I can't even 4.2 to start any more, it's just stuck at gyro initializing. flashed back to 4.1 copter reset all settings to try and clear the board but when i flash 4.2 rover i just get repeated message of "initializing". 4.1.1 rover is working fine . but i just cant get 4.2 to boot anymore. il get you a parameter list as soon as i can get it started again.

**Comment by rmackay9** [comment]
@geofrancis,

The "Initialising ArduPilot" message should be fixed if you rebase on master.  There was a bad PR that was merged yesterday but the issue has been fixed now.  Sorry for the troubles.

**Comment by geofrancis** [comment]
flashing 4.2dev via mission planner is still giving me the error.

**Comment by rmackay9** [comment]
@geofrancis, yes, the build server hasn't gotten through rebuilding all the various versions yet.  It should be fixed in a few hours though.

**Comment by shellixyz** [comment]
> @shellixyz you are using reversing motors on 4.2 I believe?

I do yes, works fine for me with Plane and BLH32

**Comment by geofrancis** [comment]
I think its something to do with the mixing in rover, as the pwm values showing on mission planner are showing the correct values and that  they are where supposed to be, but the dshot output doesn't match what its showing.

**Comment by geofrancis** [comment]
I have just done a fresh installation of 4.2, configured everything from scratch back to the way it was working in 4.1 and the problem is back, reverse is inverte
[boat.zip](https://github.com/ArduPilot/ardupilot/files/7610986/boat.zip)
d.

**Comment by andyp1per** [comment]
What flight controller is this on?

**Comment by geofrancis** [comment]
pixhawk 1

**Comment by geofrancis** [comment]
were you able to replicate this?

**Comment by geofrancis** [comment]
> Sorry, was doing other stuff over the weekend

no problem

**Comment by rmackay9** [comment]
We discussed this at the dev call today and I agreed I would try and reproduce this on a BLHeliESC that I have.

**Comment by AlksSAV** [comment]
I have the[ same problem](https://discuss.ardupilot.org/t/blheli-32-missing-parameter-servo-blh-bdmask/81064/21?u=mckey) with DShot on Rover 4.1.3 firmware. Previously there was version 4.2
My Equipment:
 - Pixhawk 2.4.8
 - BLHeli_32 DYS Aria 35A

**Comment by Jahor** [comment]
Same issue. Also in BLHeli_32 when configured in Bidirectional 3D (not Soft) sending 1048 (idle state) over DShot causes motors to spin. May be it is possible to send command 0 (stop) when idle?
When sending 1500 with PWM it does not happen, as they have some dead-band.

**Comment by rmackay9** [comment]
I've reproduced the issue on a CubeOrange running Rover-4.2.0-beta and 4.3.0-dev (aka latest, aka master) so hopefully we can get to the bottom of this.

**Comment by rmackay9** [comment]
Ok, I think we have a fix for this issue here https://github.com/ArduPilot/ardupilot/pull/20349.

@geofrancis do you think you could test this resolves the issue?  It does for me but I'd like to get it tested with various different autopilots if possible.

**Comment by geofrancis** [comment]
I have been ill for the last month, I haven't been able to test anything yet unfortunately.

**Comment by rmackay9** [comment]
@geofrancis, hope you're feeling better soon.  I've tested it quite thoroughly and the fix is included in -beta3 which should be out later today.

I think I might close this one but we can re-open if you find the problem still exists.

**Comment by AlksSAV** [comment]
Now I have tested on version 4.3 dev, still not correct work. Is it just me who has such a problem?

**Comment by andyp1per** [comment]
> Now I have tested on version 4.3 dev, still not correct work. Is it just me who has such a problem?

Please post your params

**Comment by AlksSAV** [comment]
> > Now I have tested on version 4.3 dev, still not correct work. Is it just me who has such a problem?
> 
> 
> 
> Please post your params

The problem turned out to be in ESC, tested everything works. 

Pixhawk 2.4.8, DYS Aria blheli 32.

**Comment by rmackay9** [comment]
@AlksSAV,

Great! thanks very much for the feedback.

**Comment by LimitlessGreen** [comment]
Have an Bluerobotics Basic ESC with Bluejay on Rover V4.5.7. Set the SERVO_BLH_3DMASK and have inverted reverse throttle. (Altough the servo output in Missionplanner looks normal)

**Comment by rmackay9** [comment]
Hi @LimitlessGreen,

Could you post an onboard log file?  Ideally these issues should reported in [the forums ](https://discuss.ardupilot.org/c/ardurover/arduboat/54).  Have you reported there yet?

**Comment by geofrancis** [comment]
> Hi @LimitlessGreen,
> 
> Could you post an onboard log file? Ideally these issues should reported in [the forums ](https://discuss.ardupilot.org/c/ardurover/arduboat/54). Have you reported there yet?

I tagged you about this in july 
https://discuss.ardupilot.org/t/dshot-reverse-inverted/120439/4

**Comment by andyp1per** [comment]
Please try 4.6
